### ISSUE TITLE
Missing note about bin/ folder

### ISSUE THREAD

**Issue by ghostface** [timower/KwadSim#21]
Heya,

Just a quick headsup while following the instructions from the readme it will fail and complain about a missing bin/ folder.

Maybe just add a note about having to create it :)

(It worked fine after creating the folder)

```
➜  native git:(master) scons platform=linux
scons: Reading SConscript files ...

scons: *** Path for option target_path does not exist: bin/

```

**Comment by ghostface** [comment]
Actually I am not sure why it even needs it - there is nothing in it after scons is done with its job.
Also deleting the folder and reruning scons also worked.
Deleting the build and bin folder however gives the same complaint again.
Not sure what is up here but something is glitchy :D

**Comment by Docteh** [comment]
target_path needing to be a place that exists is probably built in to scons, but its not actually used?

`scons platform=linux target_path=.` would get around it.

**Comment by timower** [comment]
I added the build/bin folder to git and added a .gitignore in each of them to prevent uploading binaries.
So I think the issues should be gone when starting from a fresh checkout.

**Comment by Docteh** [comment]
Can confirm. I did a fresh checkout last night, and no complaints about a bin folder.
