### ISSUE TITLE
Might not compile for windows

### ISSUE THREAD

**Issue by Docteh** [timower/KwadSim#22]
Has anyone tried compiling a windows build on windows? I tried compiling a windows build from linux and its complaining about a lack of `pthreads`

```
 x86_64-w64-mingw32-g++ -o build/src/serialtcpthread.os -c -DWIN32 -D_WIN32 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_DEBUG -fPIC -DSIMULATOR_BUILD -D__TARGET__=\"KWADSIM\" -D__REVISION__=\"de1c1d537\" -DHSE_VALUE=8000000 -DFLASH_SIZE=2048 -Ibuild -I. -Ibuild/godot-cpp/godot_headers -Igodot-cpp/godot_headers -Ibuild/godot-cpp/include -Igodot-cpp/include -Ibuild/godot-cpp/include/core -Igodot-cpp/include/core -Ibuild/godot-cpp/include/gen -Igodot-cpp/include/gen -Ibuild/src -Isrc -Ibuild/betaflight/lib/main/dyad -Ibetaflight/lib/main/dyad -Ibuild/betaflight/src/main -Ibetaflight/src/main -pthread src/serialtcpthread.cpp
src/serialtcpthread.cpp:18:8: error: ‘pthread_t’ does not name a type; did you mean ‘_threadid’?
 static pthread_t tcpWorker;
        ^~~~~~~~~
        _threadid
src/serialtcpthread.cpp: In member function ‘void godot::SerialTcpThread::start_tcp()’:
src/serialtcpthread.cpp:37:31: error: ‘tcpWorker’ was not declared in this scope
     int ret = pthread_create(&tcpWorker, nullptr, tcpThread, nullptr);
                               ^~~~~~~~~
src/serialtcpthread.cpp:37:15: error: ‘pthread_create’ was not declared in this scope
     int ret = pthread_create(&tcpWorker, nullptr, tcpThread, nullptr);
               ^~~~~~~~~~~~~~
src/serialtcpthread.cpp:37:15: note: suggested alternative: ‘thread_local’
     int ret = pthread_create(&tcpWorker, nullptr, tcpThread, nullptr);
               ^~~~~~~~~~~~~~
               thread_local
src/serialtcpthread.cpp: In member function ‘void godot::SerialTcpThread::stop_tcp()’:
src/serialtcpthread.cpp:46:18: error: ‘tcpWorker’ was not declared in this scope
     pthread_join(tcpWorker, nullptr);
                  ^~~~~~~~~
src/serialtcpthread.cpp:46:5: error: ‘pthread_join’ was not declared in this scope
     pthread_join(tcpWorker, nullptr);
     ^~~~~~~~~~~~
src/serialtcpthread.cpp:46:5: note: suggested alternative: ‘pthreadmbcinfo’
     pthread_join(tcpWorker, nullptr);
     ^~~~~~~~~~~~
     pthreadmbcinfo
```

This is fixed by adding `#include <pthread.h>` to src/serialtcpthread.cpp

Now I'm getting other complains about include files. I'll set this aside until I can get enough disk space to either run a linux virtual machine on my workstation, or to try compiling it inside windows...

**Comment by timower** [comment]
Hey, I recently removed the dependency on pthread and linux sockets. So normally it should compile using mingw on windows. I only tested a cross compile from linux but it should work

**Comment by Docteh** [comment]
Thanks. Getting closer. I checked out a fresh copy just now, had to comment out one last line at the top of `src/serialtcpthread.cpp`

`static pthread_t tcpWorker;`

This is my current error
```
scons: *** [build/betaflight/src/main/flight/gyroanalyse.os] Source `betaflight/src/main/flight/gyroanalyse.c' not found, needed by target `build/betaflight/src/main/flight/gyroanalyse.os'.
```


I'll uh, see if I can figure out if I can check out a slightly newer betaflight

$ git status
HEAD detached at de1c1d537
nothing to commit, working tree clean
$ git rev-parse de1c1d537
de1c1d537710a02058c13921486146053c47e232

Looks like I could go in and manually check out https://github.com/betaflight/betaflight/commit/5141bbfa944ea64549be57b1993378d1937b570e

I'll edit this comment in a bit if I can/can't run it. but it compiles. (I'm doing the same cross compiling, but I plan to actual run it on windows)

**Comment by timower** [comment]
Sorry, completely forgot to include the betaflight submodule to my commit.
I also removed the unused pthread in my latest commit.
I should look into setting up some CI system to check my commits and pull requests.

**Comment by Docteh** [comment]
in [entry] section of `Script/native/kwadsim.gdnlib` it needs an added line: 
`Windows.64="res://Script/native/build/bin/win64/libkwadsim.so"`

**Comment by timower** [comment]
done

**Comment by Docteh** [comment]
The log mentions "bind port 5761 for UART1" but I guess that might be disabled for now?

**Comment by Docteh** [comment]
Kind of off topic, but why is there .gitignore files everywhere? betaflight only has one at the root of the repository.

**Comment by timower** [comment]
No it should work, enter "tcp://127.0.0.1:5761" in the port section of the configurator and click connect after clicking fly. The simulation needs to be running for this to work, that's why it won't work while paused or in the menus
